import os

file_path = r'c:\Users\chatt\Desktop\ECO-BEM\index.html'

with open(file_path, 'r', encoding='utf-8') as f:
    html = f.read()

overlay_html = """
<!-- Annals (Past Papers) Overlay -->
<div id="ov-annals" class="overlay">
  <div class="topbar">
    <div style="font-weight:bold;font-size:1.1rem;display:flex;align-items:center;gap:10px">
      <i class="fa-solid fa-book-open"></i> حوليات BEM
    </div>
    <div class="header-icons">
      <button class="icon-btn" onclick="closeOverlay('annals')"><i class="fa-solid fa-times"></i></button>
    </div>
  </div>
  
  <!-- Step 1: Selection -->
  <div id="annals-selection" class="screen-content" style="padding:15px; overflow-y:auto; padding-bottom:100px;">
    <h3 style="margin-bottom:15px">1. اختر المادة</h3>
    <div id="annals-subjects" class="grid-2" style="gap:10px;margin-bottom:25px">
      <!-- Subjects generated by JS -->
    </div>
    
    <div id="annals-years-container" style="display:none;">
      <h3 style="margin-bottom:15px">2. اختر السنة - <span id="annals-selected-subject-name" style="color:var(--primary-color)"></span></h3>
      <div id="annals-years" class="grid-4" style="gap:10px">
        <!-- Years generated by JS -->
      </div>
    </div>
  </div>

  <!-- Step 2: Split Screen Workspace -->
  <div id="annals-workspace" class="screen-content" style="display:none; padding:0; flex-direction:column; height:calc(100vh - 60px);">
    
    <!-- Top Half: PDF Viewer -->
    <div id="annals-pdf-container" style="flex:1; border-bottom: 2px solid var(--border-color); position:relative; background:#fff;">
      <iframe id="annals-iframe" src="" style="width:100%; height:100%; border:none;"></iframe>
    </div>
    
    <!-- Bottom Half: Student Workspace -->
    <div style="flex:1; display:flex; flex-direction:column; background:var(--bg-card); padding:10px;">
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;">
        <div style="font-weight:bold; color:var(--text-color)"><i class="fa-solid fa-pen"></i> مساحة المحاولة (مسودة)</div>
        <button id="annals-toggle-btn" class="btn btn-primary" onclick="toggleAnnalsSolution()" style="padding:5px 15px; font-size:0.9rem;">
          <i class="fa-solid fa-eye"></i> عرض الحل
        </button>
      </div>
      <textarea placeholder="اكتب محاولتك هنا أو استخدم ورقة خارجية وقارن حلك..." style="flex:1; width:100%; border-radius:10px; padding:15px; background:var(--bg-main); color:var(--text-color); border:1px solid var(--border-color); resize:none; font-family:inherit; font-size:1rem;"></textarea>
    </div>
    
  </div>
</div>
"""

# Just inject it before the last </div>
if 'id="ov-annals"' not in html:
    html = html.replace('</div>\n</body>', overlay_html + '\n</div>\n</body>')

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(html)

print("Injected ov-annals!")
