import os
import re

file_path = r'c:\Users\chatt\Desktop\ECO-BEM\index.html'

with open(file_path, 'r', encoding='utf-8') as f:
    html = f.read()

floating_button_overlay = """
<!-- Annals (Past Papers) Overlay -->
<div id="ov-annals" class="overlay" style="z-index:99999;">
  <div class="topbar">
    <div style="font-weight:bold;font-size:1.1rem;display:flex;align-items:center;gap:10px">
      <i class="fa-solid fa-book-open"></i> حوليات BEM
    </div>
    <div class="header-icons">
      <button class="icon-btn" onclick="closeOverlay('annals')"><i class="fa-solid fa-times"></i></button>
    </div>
  </div>
  
  <!-- Step 1: Selection -->
  <div id="annals-selection" class="screen-content" style="padding:15px; overflow-y:auto; padding-bottom:100px;">
    <h3 style="margin-bottom:15px">1. اختر المادة</h3>
    <div id="annals-subjects" class="grid-2" style="gap:10px;margin-bottom:25px">
      <!-- Subjects generated by JS -->
    </div>
    
    <div id="annals-years-container" style="display:none;">
      <h3 style="margin-bottom:15px">2. اختر السنة - <span id="annals-selected-subject-name" style="color:var(--primary-color)"></span></h3>
      <div id="annals-years" class="grid-4" style="gap:10px">
        <!-- Years generated by JS -->
      </div>
    </div>
  </div>

  <!-- Step 2: Full Screen PDF Viewer -->
  <div id="annals-workspace" class="screen-content" style="display:none; padding:0; height:calc(100vh - 60px); position:relative;">
    
    <div id="annals-pdf-container" style="width:100%; height:100%; background:#fff;">
      <iframe id="annals-iframe" src="" style="width:100%; height:100%; border:none;"></iframe>
    </div>
    
    <!-- Floating Attempt Button -->
    <button id="floating-attempt-btn" onclick="openAttemptModal()" class="btn btn-primary" style="position:absolute; bottom:20px; left:50%; transform:translateX(-50%); padding:12px 25px; font-size:1.1rem; border-radius:30px; box-shadow:0 4px 15px rgba(0,0,0,0.5); z-index:100; border:2px solid #fff;">
      <i class="fa-solid fa-pen"></i> مساحة المحاولة (إجبارية)
    </button>
    
    <!-- Floating Back to Subject Button (Hidden initially) -->
    <button id="floating-back-btn" onclick="toggleAnnalsSolution()" class="btn btn-outline" style="display:none; position:absolute; bottom:20px; left:50%; transform:translateX(-50%); padding:12px 25px; font-size:1.1rem; border-radius:30px; box-shadow:0 4px 15px rgba(0,0,0,0.5); z-index:100; background:var(--bg); border:2px solid var(--primary-color);">
      <i class="fa-solid fa-file-pdf"></i> العودة للموضوع
    </button>
    
    <!-- Attempt Modal -->
    <div id="attempt-modal" style="display:none; position:absolute; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.8); z-index:200; justify-content:center; align-items:center; padding:20px;">
      <div style="background:var(--bg-card); width:100%; max-width:500px; border-radius:15px; padding:20px; display:flex; flex-direction:column; border:1px solid var(--border-color);">
        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;">
          <h3 style="margin:0;"><i class="fa-solid fa-pen"></i> مسودتك (إجبارية)</h3>
          <button class="icon-btn" onclick="closeAttemptModal()"><i class="fa-solid fa-times"></i></button>
        </div>
        <p style="color:var(--text-muted); font-size:0.9rem; margin-bottom:10px;">لن يتم كشف الحل النموذجي حتى تقوم بكتابة محاولتك هنا (على الأقل 20 حرفاً) لإثبات مجهودك.</p>
        <textarea id="attempt-textarea" placeholder="اكتب أفكارك، طريقة حلك، أو مسودتك هنا..." style="width:100%; height:150px; background:var(--bg-main); color:var(--text-color); border:1px solid var(--border-color); border-radius:10px; padding:15px; resize:none; font-family:inherit; margin-bottom:15px;"></textarea>
        
        <button class="btn btn-primary" onclick="submitAttempt()" style="width:100%; padding:12px; font-size:1rem;">
          <i class="fa-solid fa-eye"></i> عرض الحل النموذجي
        </button>
      </div>
    </div>
    
  </div>
</div>
"""

# Replace the old ov-annals with the new one
html = re.sub(r'<!-- Annals \(Past Papers\) Overlay -->\s*<div id="ov-annals" class="overlay">.*?</div>\s*</div>\s*</div>', '\n' + floating_button_overlay, html, flags=re.DOTALL)

# Also update the JS to app.v9.js which has the attempt modal functions
html = html.replace('<script src="app.v7.js"></script>', '<script src="app.v9.js"></script>')

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(html)

print("Upgraded to floating button design!")
